[project]
name = "polars-experience"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair>=5.5.0",
    "deltalake>=0.23.1",
    "duckdb>=1.1.3",
    "numpy>=2.2.1",
    "packaging>=24.2",
    "polars>=1.19.0",
]
